# coding: utf-8

"""
    EPA (Event Posting App) API

    API for a mobile safety application that allows users to post and subscribe to local safety concerns. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI, Request

from epa_api.apis.authentication_api import router as AuthenticationApiRouter
from epa_api.apis.system_api import router as SystemApiRouter
from epa_api.api_implementation.utils.context import current_token_data
from epa_api.models.extra_models import TokenModel

app = FastAPI(
    title="EPA (Event Posting App) API",
    description="API for a mobile safety application that allows users to post and subscribe to local safety concerns. ",
    version="1.0.0",
)

@app.middleware("http")
async def persist_auth_context(request: Request, call_next):
    
    print("tmp")
    auth_header = request.headers.get("Authorization")
    
    if auth_header and auth_header.lower().startswith("bearer "):
        try:
            token_str = auth_header.split(" ")[1]
            token_model = TokenModel(sub=token_str)
            current_token_data.set(token_model)
        except Exception:
             # Let the Security dependency handle formal errors
            pass
            
    # Proceed to the Router -> Security Dependency -> Implementation
    response = await call_next(request)
    return response
    
app.include_router(AuthenticationApiRouter)
app.include_router(SystemApiRouter)
